### ISSUE TITLE
Implement an insert and swap bar feature

### ISSUE THREAD

**Issue by jwyf** [AY1920S1-CS2113T-F09-4/main#139]
Implement insertbar and swapbar commands so that the user can use and navigate the Ducats in a more straightforward and fast manner.
The InsertBarCommand is for users to be able to insert a bar in between existing bars in one command.
The SwapBarCommand is for users to be able to swap the position of two existing bars in one command.

**Comment by Samuel787** [comment]
Hey Joseph, for insertbar, they can just use Copy command.
For example, if they want to insert bar 3 into index 5, they can do:
copy <start_num> <end_num> <index_to_paste>
copy 3 3 5
You can test it out by:
ascii song <song_name>
copy <start_num> <end_num> <index_to_paste>
ascii song <song_name>

**Comment by Samuel787** [comment]
Swap is a very good idea!
